version: "3.9"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'celery -A crypto.celery worker --loglevel=DEBUG'
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'celery -A crypto.celery beat --loglevel=DEBUG'
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker


  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - '6379:6379'